### ISSUE TITLE
[RFC] Separate into multiple packages

### ISSUE THREAD

**Issue by rthor** [aranja/tux#1]
# Packages

Offline, we agreed on that the project should be managed in a monorepo fashion. The unanswered questions are: 

- What should the separate packages contain?
- How should we manage dependencies?

Below I outline one proposal for tackling those questions.

### Packages

- **@tux/provider**: Everything concerning the Contentful integrations. Eg `connect`, `provider`, etc.
- **@tux/components**: Components for rendering/editing data from the _@tux/provider._  Eg `<Editable />`. These should probably not be coupled directly with specifics of the API. It shouldn't care what "backend" is being used, only generically fetch and post data [somehow]. 
- **@tux/admin** This would be the main entry point for the admin itself.  It will either need to:
  - support multiple sites,
  - or, be easy to replicate for different sites.

### Dependency management 

We don't really have that much to maintain in the beginning so maybe this isn't something to worry about. I just think that having this solid to start with will be beneficial in the long run. I recommend we use [lerna]( https://lernajs.io/) with the `--independent` flag so that single package updates will be simple.

## [Possible] Drawbacks

- It might be hard to decouple `@tux/provider` and `@tux/components` in practice.
- Lerna forces a very strict folder structure.

**Comment by thorsteinsson** [comment]
I agree with using Lerna. It would be good to set it up in a different repo and move away from this hack 😄 

I'd like to see the contentful integration in a separate package, so we could have `tux-provider-contentful` and `tux-provider-wordpress`.

Can we find a better name for the admin package or just call it tux for now? I think of admin as a separate site, even a hosted one.

**Comment by eirikurn** [comment]
Agree on separating comtent integration.

Not sure what you consider admin, but we should expose the core react
provider and editing integrations as tux, for now.

**Comment by thorsteinsson** [comment]
We could to it like Babel and call it `tux-core`.

**Comment by eirikurn** [comment]
They have babel-core because the same transpiler is exposed through
multiple different interfaces (babel-cli, babel-register, babel-eslint,
etc).

**Comment by thorsteinsson** [comment]
Good point.

**Comment by eirikurn** [comment]
I think we're in a good place now with lerna and the current separation of tux and adapters. We can separate more later when appropriate. 

@rthor do we close this issue or keep it alive somehow?

**Comment by rthor** [comment]
We close it. Good job on implementing all this!!!! 🎉  👍  🤗
