### ISSUE TITLE
Problems running lerna bootstrap

### ISSUE THREAD

**Issue by benediktvaldez** [aranja/tux#105]
Tried running `lerna bootstrap` – which makes sense since this seems to be a lerna monorepo, worked fine until it tried to run the prepublish on `tux-cli`, at which point it pretends to not find `yargs` (although it is clearly installed in `tux-cli`'s node_modules)

Not sure what the problem is, I'll leave the whole `lerna-debug.log` here if someone would like to dissect it. Not really a blocker for me, but might revisit if help is needed.

<details><summary>lerna-debug.log</summary>
raw output from lerna-debug.log

    lerna(verbose) GitUtilities.isInitialized    ()
    lerna(verbose) GitUtilities.isInitialized    () => true
    lerna(verbose) GitUtilities.getTopLevelDirectory()
    lerna(verbose) GitUtilities.getTopLevelDirectory() => "."
    lerna(verbose) FileSystemUtilities.existsSync("./lerna.json")
    lerna(verbose) FileSystemUtilities.existsSync("./lerna.json") => true
    lerna(verbose) FileSystemUtilities.readFileSync("./lerna.json")
    lerna(verbose) FileSystemUtilities.readFileSync("./lerna.json") => "{\n  \"lerna\": \"2.0.0-beta.38\",\n  \"packages\": [\n    \"packages/*\"\n  ],\n  \"version\": \"independent\"\n}"
    lerna(verbose) FileSystemUtilities.existsSync("./package.json")
    lerna(verbose) FileSystemUtilities.existsSync("./package.json") => true
    lerna(verbose) FileSystemUtilities.readFileSync("./package.json")
    lerna(verbose) FileSystemUtilities.readFileSync("./package.json") => "{\n  \"private\": true,\n  \"license\": \"MIT\",\n  \"scripts\": {\n    \"start\": \"cd packages/tux-example-site && npm start\",\n    \"postinstall\": \"npm run bootstrap\",\n    \"lint\": \"tslint -c './tslint.json' -e './packages/**/node_modules/**/*' -e './packages/**/es/**/*' -e './packages/**/lib/**/*' './packages/**/*.{ts,tsx}'\",\n    \"lerna\": \"lerna\",\n    \"bootstrap\": \"lerna bootstrap --hoist\",\n    \"watch\": \"lerna run watch --stream --no-sort\",\n    \"test\": \"lerna run test\"\n  },\n  \"dependencies\": {\n    \"@types/react-day-picker\": \"^1.2.37\",\n    \"core-js\": \"2.4.1\",\n    \"moment\": \"^2.17.1\",\n    \"react\": \"15.4.2\",\n    \"react-day-picker\": \"^5.1.1\",\n    \"react-dom\": \"15.4.2\",\n    \"react-icons\": \"^2.2.3\",\n    \"typescript\": \"^2.2.2\"\n  },\n  \"devDependencies\": {\n    \"@types/chalk\": \"^0.4.31\",\n    \"@types/classnames\": \"0.0.32\",\n    \"@types/enzyme\": \"^2.7.5\",\n    \"@types/express\": \"^4.0.35\",\n    \"@types/jest\": \"^18.1.1\",\n    \"@types/lodash\": \"^4.14.61\",\n    \"@types/material-ui\": \"^0.16.48\",\n    \"@types/mz\": \"0.0.30\",\n    \"@types/moment\": \"^2.13.0\",\n    \"@types/node\": \"^7.0.4\",\n    \"@types/ramda\": \"0.0.5\",\n    \"@types/react\": \"^15.0.4\",\n    \"@types/react-addons-css-transition-group\": \"^15.0.1\",\n    \"@types/react-dom\": \"^0.14.21\",\n    \"@types/semver\": \"^5.3.31\",\n    \"@types/webpack\": \"^2.2.7\",\n    \"@types/webpack-chain\": \"^3.0.0\",\n    \"@types/yargs\": \"^6.6.0\",\n    \"babel-jest\": \"^18.0.0\",\n    \"babel-plugin-transform-runtime\": \"^6.23.0\",\n    \"babel-preset-es2015\": \"^6.24.1\",\n    \"babel-preset-react\": \"^6.24.1\",\n    \"del\": \"^2.2.2\",\n    \"enzyme\": \"^2.7.1\",\n    \"gulp\": \"^3.9.1\",\n    \"gulp-babel\": \"^6.1.2\",\n    \"gulp-cli\": \"^1.2.2\",\n    \"gulp-clone\": \"^1.0.0\",\n    \"gulp-sourcemaps\": \"^2.4.1\",\n    \"gulp-typescript\": \"^3.1.4\",\n    \"gulp-util\": \"^3.0.8\",\n    \"jest\": \"^18.1.0\",\n    \"lerna\": \"2.0.0-beta.38\",\n    \"merge2\": \"^1.0.3\",\n    \"react-addons-test-utils\": \"15.4.2\",\n    \"react-hot-loader\": \"^3.0.0-beta.6\",\n    \"react-test-renderer\": \"15.4.2\",\n    \"run-sequence\": \"^1.2.2\",\n    \"styled-jsx\": \"^0.5.4\",\n    \"tslint\": \"^5.0.0\",\n    \"typescript\": \"^2.1.5\",\n    \"webpack\": \"^2.2.1\",\n    \"yargs\": \"^6.6.0\"\n  },\n  \"babel\": {\n    \"env\": {\n      \"test\": {\n        \"plugins\": [\n          \"styled-jsx/babel\",\n          [\n            \"transform-runtime\",\n            {\n              \"helpers\": false,\n              \"polyfill\": false,\n              \"regenerator\": true\n            }\n          ]\n        ],\n        \"presets\": [\n          \"react\",\n          \"es2015\"\n        ]\n      }\n    }\n  }\n}"
    lerna(info)    Lerna v2.0.0-beta.38
    lerna(info)    Independent Versioning Mode
    lerna(verbose) FileSystemUtilities.existsSync("./package.json")
    lerna(verbose) FileSystemUtilities.existsSync("./package.json") => true
    lerna(verbose) FileSystemUtilities.existsSync("./lerna.json")
    lerna(verbose) FileSystemUtilities.existsSync("./lerna.json") => true
    lerna(verbose) FileSystemUtilities.existsSync("./VERSION")
    lerna(verbose) FileSystemUtilities.existsSync("./VERSION") => false
    lerna(verbose) FileSystemUtilities.existsSync("./packages/jsx-html-webpack-plugin/package.json")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/jsx-html-webpack-plugin/package.json") => true
    lerna(verbose) FileSystemUtilities.existsSync("./packages/neutrino-preset-tux/package.json")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/neutrino-preset-tux/package.json") => true
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-adapter-contentful/package.json")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-adapter-contentful/package.json") => true
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-cli/package.json")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-cli/package.json") => true
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-example-site/package.json")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-example-site/package.json") => true
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-scripts/package.json")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-scripts/package.json") => true
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux/package.json")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux/package.json") => true
    lerna(verbose) Attempting running BootstrapCommand.initialize
    lerna(verbose) Successfully ran BootstrapCommand.initialize
    lerna(verbose) Attempting running BootstrapCommand.execute
    lerna(info)    Bootstrapping 7 packages
    lerna(info)    Preinstalling packages
    lerna(info)    Symlinking packages and binaries
    lerna(verbose) FileSystemUtilities.existsSync("./packages/jsx-html-webpack-plugin/package.json")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/jsx-html-webpack-plugin/package.json") => true
    lerna(verbose) FileSystemUtilities.existsSync("./packages/neutrino-preset-tux/node_modules/jsx-html-webpack-plugin")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/neutrino-preset-tux/node_modules/jsx-html-webpack-plugin") => true
    lerna(verbose) FileSystemUtilities.isSymlink ("./packages/neutrino-preset-tux/node_modules/jsx-html-webpack-plugin")
    lerna(verbose) FileSystemUtilities.isSymlink ("./packages/neutrino-preset-tux/node_modules/jsx-html-webpack-plugin") => "./packages/jsx-html-webpack-plugin"
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux/package.json")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux/package.json") => true
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-adapter-contentful/node_modules/tux")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-adapter-contentful/node_modules/tux") => true
    lerna(verbose) FileSystemUtilities.isSymlink ("./packages/tux-adapter-contentful/node_modules/tux")
    lerna(verbose) FileSystemUtilities.isSymlink ("./packages/tux-adapter-contentful/node_modules/tux") => "./packages/tux"
    lerna(verbose) FileSystemUtilities.existsSync("./packages/neutrino-preset-tux/package.json")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/neutrino-preset-tux/package.json") => true
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-example-site/node_modules/neutrino-preset-tux")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-example-site/node_modules/neutrino-preset-tux") => true
    lerna(verbose) FileSystemUtilities.isSymlink ("./packages/tux-example-site/node_modules/neutrino-preset-tux")
    lerna(verbose) FileSystemUtilities.isSymlink ("./packages/tux-example-site/node_modules/neutrino-preset-tux") => "./packages/neutrino-preset-tux"
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux/package.json")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux/package.json") => true
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-example-site/node_modules/tux")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-example-site/node_modules/tux") => true
    lerna(verbose) FileSystemUtilities.isSymlink ("./packages/tux-example-site/node_modules/tux")
    lerna(verbose) FileSystemUtilities.isSymlink ("./packages/tux-example-site/node_modules/tux") => "./packages/tux"
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-scripts/package.json")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-scripts/package.json") => true
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-example-site/node_modules/tux-scripts")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-example-site/node_modules/tux-scripts") => true
    lerna(verbose) FileSystemUtilities.isSymlink ("./packages/tux-example-site/node_modules/tux-scripts")
    lerna(verbose) FileSystemUtilities.isSymlink ("./packages/tux-example-site/node_modules/tux-scripts") => "./packages/tux-scripts"
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-adapter-contentful/package.json")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-adapter-contentful/package.json") => true
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-example-site/node_modules/tux-adapter-contentful")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-example-site/node_modules/tux-adapter-contentful") => true
    lerna(verbose) FileSystemUtilities.isSymlink ("./packages/tux-example-site/node_modules/tux-adapter-contentful")
    lerna(verbose) FileSystemUtilities.isSymlink ("./packages/tux-example-site/node_modules/tux-adapter-contentful") => "./packages/tux-adapter-contentful"
    lerna(verbose) FileSystemUtilities.existsSync("./packages/neutrino-preset-tux/package.json")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/neutrino-preset-tux/package.json") => true
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-scripts/node_modules/neutrino-preset-tux")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-scripts/node_modules/neutrino-preset-tux") => true
    lerna(verbose) FileSystemUtilities.isSymlink ("./packages/tux-scripts/node_modules/neutrino-preset-tux")
    lerna(verbose) FileSystemUtilities.isSymlink ("./packages/tux-scripts/node_modules/neutrino-preset-tux") => "./packages/neutrino-preset-tux"
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux/package.json")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux/package.json") => true
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-scripts/node_modules/tux")
    lerna(verbose) FileSystemUtilities.existsSync("./packages/tux-scripts/node_modules/tux") => true
    lerna(verbose) FileSystemUtilities.isSymlink ("./packages/tux-scripts/node_modules/tux")
    lerna(verbose) FileSystemUtilities.isSymlink ("./packages/tux-scripts/node_modules/tux") => "./packages/tux"
    lerna(verbose) FileSystemUtilities.mkdirp    ("./packages/neutrino-preset-tux/node_modules")
    lerna(verbose) FileSystemUtilities.mkdirp    ("./packages/neutrino-preset-tux/node_modules") => null
    lerna(verbose) FileSystemUtilities.symlink   ("./packages/jsx-html-webpack-plugin", "./packages/neutrino-preset-tux/node_modules/jsx-html-webpack-...)
    lerna(verbose) FileSystemUtilities.symlink   ("./packages/jsx-html-webpack-plugin", "./packages/neutrino-preset-tux/node_modules/jsx-html-webpack-...) => 
    lerna(verbose) FileSystemUtilities.mkdirp    ("./packages/tux-adapter-contentful/node_modules")
    lerna(verbose) FileSystemUtilities.mkdirp    ("./packages/tux-adapter-contentful/node_modules") => null
    lerna(verbose) FileSystemUtilities.symlink   ("./packages/tux", "./packages/tux-adapter-contentful/node_modules/tux", "junction")
    lerna(verbose) FileSystemUtilities.symlink   ("./packages/tux", "./packages/tux-adapter-contentful/node_modules/tux", "junction") => 
    lerna(verbose) FileSystemUtilities.mkdirp    ("./packages/tux-example-site/node_modules")
    lerna(verbose) FileSystemUtilities.mkdirp    ("./packages/tux-example-site/node_modules") => null
    lerna(verbose) FileSystemUtilities.symlink   ("./packages/neutrino-preset-tux", "./packages/tux-example-site/node_modules/neutrino-preset-tux", "j...)
    lerna(verbose) FileSystemUtilities.symlink   ("./packages/neutrino-preset-tux", "./packages/tux-example-site/node_modules/neutrino-preset-tux", "j...) => 
    lerna(verbose) FileSystemUtilities.mkdirp    ("./packages/tux-example-site/node_modules")
    lerna(verbose) FileSystemUtilities.mkdirp    ("./packages/tux-example-site/node_modules") => null
    lerna(verbose) FileSystemUtilities.symlink   ("./packages/tux", "./packages/tux-example-site/node_modules/tux", "junction")
    lerna(verbose) FileSystemUtilities.symlink   ("./packages/tux", "./packages/tux-example-site/node_modules/tux", "junction") => 
    lerna(verbose) FileSystemUtilities.mkdirp    ("./packages/tux-example-site/node_modules")
    lerna(verbose) FileSystemUtilities.mkdirp    ("./packages/tux-example-site/node_modules") => null
    lerna(verbose) FileSystemUtilities.symlink   ("./packages/tux-scripts", "./packages/tux-example-site/node_modules/tux-scripts", "junction")
    lerna(verbose) FileSystemUtilities.symlink   ("./packages/tux-scripts", "./packages/tux-example-site/node_modules/tux-scripts", "junction") => 
    lerna(verbose) FileSystemUtilities.mkdirp    ("./packages/tux-example-site/node_modules/.bin")
    lerna(verbose) FileSystemUtilities.mkdirp    ("./packages/tux-example-site/node_modules/.bin") => null
    lerna(verbose) FileSystemUtilities.symlink   ("./packages/tux-scripts/bin/tux-scripts", "./packages/tux-example-site/node_modules/.bin/tux-scripts...)
    lerna(verbose) FileSystemUtilities.symlink   ("./packages/tux-scripts/bin/tux-scripts", "./packages/tux-example-site/node_modules/.bin/tux-scripts...) => 
    lerna(verbose) FileSystemUtilities.mkdirp    ("./packages/tux-example-site/node_modules")
    lerna(verbose) FileSystemUtilities.mkdirp    ("./packages/tux-example-site/node_modules") => null
    lerna(verbose) FileSystemUtilities.symlink   ("./packages/tux-adapter-contentful", "./packages/tux-example-site/node_modules/tux-adapter-contentfu...)
    lerna(verbose) FileSystemUtilities.symlink   ("./packages/tux-adapter-contentful", "./packages/tux-example-site/node_modules/tux-adapter-contentfu...) => 
    lerna(verbose) FileSystemUtilities.mkdirp    ("./packages/tux-scripts/node_modules")
    lerna(verbose) FileSystemUtilities.mkdirp    ("./packages/tux-scripts/node_modules") => null
    lerna(verbose) FileSystemUtilities.symlink   ("./packages/neutrino-preset-tux", "./packages/tux-scripts/node_modules/neutrino-preset-tux", "juncti...)
    lerna(verbose) FileSystemUtilities.symlink   ("./packages/neutrino-preset-tux", "./packages/tux-scripts/node_modules/neutrino-preset-tux", "juncti...) => 
    lerna(verbose) FileSystemUtilities.mkdirp    ("./packages/tux-scripts/node_modules")
    lerna(verbose) FileSystemUtilities.mkdirp    ("./packages/tux-scripts/node_modules") => null
    lerna(verbose) FileSystemUtilities.symlink   ("./packages/tux", "./packages/tux-scripts/node_modules/tux", "junction")
    lerna(verbose) FileSystemUtilities.symlink   ("./packages/tux", "./packages/tux-scripts/node_modules/tux", "junction") => 
    lerna(info)    Postinstalling packages
    lerna(info)    Prepublishing packages
    lerna(verbose) NpmUtilities.runScriptInDir   ("prepublish", [], "./packages/tux-cli")
    lerna(verbose) NpmUtilities.execInDir        ("run prepublish", [], "./packages/tux-cli")
    lerna(verbose) NpmUtilities.runScriptInDir   ("prepublish", [], "./packages/tux")
    lerna(verbose) NpmUtilities.execInDir        ("run prepublish", [], "./packages/tux")
    lerna(error)   NpmUtilities.execInDir        ("run prepublish", [], "./packages/tux-cli")
        Error: Command failed: npm run prepublish 
        module.js:472
            throw err;
            ^
        
        Error: Cannot find module 'yargs'
            at Function.Module._resolveFilename (module.js:470:15)
            at Function.Module._load (module.js:418:25)
            at Module.require (module.js:498:17)
            at require (internal/module.js:20:19)
            at Object.<anonymous> (/Users/benediktvaldez/code/tux/tasks/build-package.js:7:14)
            at Module._compile (module.js:571:32)
            at Object.Module._extensions..js (module.js:580:10)
            at Module.load (module.js:488:32)
            at tryModuleLoad (module.js:447:12)
            at Function.Module._load (module.js:439:3)
        
        npm ERR! Darwin 16.4.0
        npm ERR! argv "/usr/local/Cellar/node/7.8.0/bin/node" "/usr/local/bin/npm" "run" "prepublish"
        npm ERR! node v7.8.0
        npm ERR! npm  v4.2.0
        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! tux-cli@0.1.0 prepublish: `TARGET=commonjs NODE_ENV=production ../../tasks/build-package.js`
        npm ERR! Exit status 1
        npm ERR! 
        npm ERR! Failed at the tux-cli@0.1.0 prepublish script 'TARGET=commonjs NODE_ENV=production ../../tasks/build-package.js'.
        npm ERR! Make sure you have the latest version of node.js and npm installed.
        npm ERR! If you do, this is most likely a problem with the tux-cli package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     TARGET=commonjs NODE_ENV=production ../../tasks/build-package.js
        npm ERR! You can get information on how to open an issue for this project with:
        npm ERR!     npm bugs tux-cli
        npm ERR! Or if that isn't available, you can get their info via:
        npm ERR!     npm owner ls tux-cli
        npm ERR! There is likely additional logging output above.
        
        npm ERR! Please include the following file with any support request:
        npm ERR!     /Users/benediktvaldez/.npm/_logs/2017-04-14T16_50_15_559Z-debug.log
        
            at ChildProcess.exithandler (child_process.js:205:12)
            at emitTwo (events.js:106:13)
            at ChildProcess.emit (events.js:194:7)
            at maybeClose (internal/child_process.js:899:16)
            at Socket.<anonymous> (internal/child_process.js:342:11)
            at emitOne (events.js:96:13)
            at Socket.emit (events.js:191:7)
            at Pipe._handle.close [as _onclose] (net.js:509:12)
    lerna(error)   
    > tux-cli@0.1.0 prepublish /Users/benediktvaldez/code/tux/packages/tux-cli
    > TARGET=commonjs NODE_ENV=production ../../tasks/build-package.js

    lerna(error)   NpmUtilities.runScriptInDir   ("prepublish", [], "./packages/tux-cli")
    lerna(error)   
    > tux-cli@0.1.0 prepublish /Users/benediktvaldez/code/tux/packages/tux-cli
    > TARGET=commonjs NODE_ENV=production ../../tasks/build-package.js

    lerna(error)   Errored while running BootstrapCommand.execute

</details>

**Comment by rthor** [comment]
You seem to be missing some packages. Did you run `npm install`? Note that it does run `lerna bootstrap` post install.

**Comment by benediktvaldez** [comment]
I made assumptions, ignored the documentation and went straight for `lerna bootstrap`

Never mind 🙃
