### ISSUE TITLE
Missing icons in TuxFab

### ISSUE THREAD

**Issue by benediktvaldez** [aranja/tux#107]
Created my fancy new project by running `tux new awesome-project`

But I don't seem to get any icons. Is that by design? Feels like it shouldn't, so here's an issue 🎁 

![](http://d.pr/i/rY9b/28CkMwjn+)

**Comment by rthor** [comment]
This was fixed in #103 but hasn't been published yet. Ping @eirikurn

**Comment by eirikurn** [comment]
Ah, sorry. It's published now.
