### ISSUE TITLE
Rename clientId in contentful adapter to something more relatable

### ISSUE THREAD

**Issue by benediktvaldez** [aranja/tux#109]
`tux-adapter-contentful` takes an option called `clientId` which had me confused for a while since I couldn't find anything called `clientId` from contentful. Turns out they call it different things, meaning that `clientId` turned out to be my applications `Uid`

I can see why you went with `clientId` in the first place since where you use it (in the 'log in' path to contentful) it is called `client_id` – but from an outsiders perspective, the developer that never really considers this path, this is like I mentioned before my applications `Uid`

My suggestion would be to name it something like `applicationUid`.

What say thee?

**Comment by eirikurn** [comment]
Good point. I like `applicationUid`. Fixing this now.
