### ISSUE TITLE
Improve the new site template

### ISSUE THREAD

**Issue by eirikurn** [aranja/tux#112]
- [x] Should have a bit more (still minimal) render output.
- [ ] Fetch a model and render it with Editable?
- [ ] Better readme. Document `app.js` contract.

**Comment by benediktvaldez** [comment]
The start script should also look like this, since HTTPS is required for contentful login, and port 3000 is assumed in new's app.js

`"start": "PORT=3000 HTTPS=true tux-scripts start",`

If #113 gets merged, we could even skip the `PORT` var

`"start": "HTTPS=true tux-scripts start",`

**Comment by thorsteinsson** [comment]
In Ember they have a welcome page component and a package. Might be nice to do it that way so it's easy to remove and we can show guides with the next steps on the page itself.

**Comment by benediktvaldez** [comment]
I agree @thorsteinsson – same with storybook, you always get a 'Welcome' story that explains how stuff works and a 'Button' story as a secondary example.

**Comment by eirikurn** [comment]
We're moving the admin logic (and contentful config) into a tux addon. The site template will be updated to match. We're also finally working on more documentation that can be added to the readme.

**Comment by eirikurn** [comment]
This is completely different and better in v0.4 (no admin stuff by default). We'll look into creating a better admin template later.
