### ISSUE TITLE
Console error message formatting failure

### ISSUE THREAD

**Issue by DavidBachmann** [aranja/tux#119]
Terminal output:

![image](https://cloud.githubusercontent.com/assets/8494120/26151142/f62cd232-3af0-11e7-97cc-2ec00c41df2e.png)

Console output:

![image](https://cloud.githubusercontent.com/assets/8494120/26151125/df734e2c-3af0-11e7-8505-841c51cbfe9e.png)

**Comment by eirikurn** [comment]
This is fixed in tux@3.0
