### ISSUE TITLE
tux.svg in /src throws error ENAMETOOLONG

### ISSUE THREAD

**Issue by herrhelms** [aranja/tux#144]
I get this error when using `yarn start` (n7.0.0)

```Error: ENAMETOOLONG: name too long, stat '/Users/seb/Sites/tux/my-app/src/"data:image/svg+xml,<svg xmlns='http:/www.w3.org/2000/svg' viewBox='0 0 496.1 367.5' style='enable-background:new 0 0 496.1 367.5;'> <path d='M93.8 277.9c-4 .7-7.8 1.1-11.6 1.1-13.4 0-23-3.8-28.8-11.4-5.7-7.6-8.6-17.1-8.6-28.6V109.8H7.5v-7.1h37V52.3h8.2v50.4h50.4v7.1H52.7V239c0 11.7 2.9 20.1 8.6 25.2 5.7 5.1 13.3 7.7 22.8 7.7 7 0 13.3-1.1 19.1-3.4l1.1 6.4c-3.1 1.2-6.6 2.2-10.5 3z'/> <path d='M267.7 250.8c-4.6 6.4-9.9 11.6-15.9 15.9-6 4.2-12.5 7.5-19.4 9.7-7 2.2-14.2 3.4-21.7 3.4-12 0-21.9-2.1-29.9-6.4-8-4.2-14.3-9.8-19.1-16.8-4.7-7-8.1-14.8-10.1-23.5s-3-17.6-3-26.5V102.7h8.2v103.1c0 7.2.7 14.8 2.2 22.6 1.5 7.8 4.3 15 8.4 21.5 4.1 6.5 9.6 11.9 16.4 16.2 6.8 4.4 15.7 6.5 26.7 6.5 9.5 0 18.4-1.9 26.7-5.8s15.6-9.4 21.7-16.6c6.1-7.2 11-16 14.6-26.3 3.6-10.3 5.4-22.1 5.4-35.3v-85.9h8.2v128.5c0 2.7.1 6.1.2 10.1s.2 8 .4 12.1c.1 4.1.3 8 .6 11.8.2 3.7.5 6.9.7 9.3h-8.2c-.3-2.5-.4-5.6-.6-9.3-.1-3.7-.3-7.8-.4-12.1-.1-4.4-.3-8.6-.4-12.7-.1-4.1-.2-7.8-.2-11h-.7c-2.6 7.9-6.2 15.1-10.8 21.4z'/> <path d='M410.9 189.4l-62.8 85.2h-10.5l68-90.8-59.4-81.1h10.5l54.5 75.5 54.2-75.5h10.8l-59.8 81.1 69.1 90.8h-10.8l-63.8-85.2z'/> </svg>"'``` 

this being the tux.svg in `/src`

**Comment by eirikurn** [comment]
Yeah, sorry, this is a recent upstream regression: https://github.com/mozilla-neutrino/neutrino-dev/issues/272

Until neutrino (or tux) updates to fix this issue, you can create a `.neutrinorc.js` file in your project root with this:

```
module.exports = {
  use: [
    'neutrino-preset-tux',

    // Fix svg imports: https://github.com/mozilla-neutrino/neutrino-dev/issues/272
    neutrino => {
      neutrino.config.module
        .rule('svg')
        .use('url')
        .loader(require.resolve('file-loader'))
        .options({ limit: 8192 })
    },
  ],
}
```
