### ISSUE TITLE
Be able to edit image fields

### ISSUE THREAD

**Issue by baering** [aranja/tux#15]
- Create a component to render fields with images
- Be able to:
  - Add a new image
  - Change an existing image
  - Remove image

**Comment by eirikurn** [comment]
What's the status of this issue?

**Comment by baering** [comment]
It is possible to add a new image and change an existing image. Removing an image is not yet supported. Maybe we should remove it from the list of requirements, since it does not apply for what we are doing (yet?).

**Comment by eirikurn** [comment]
Great. I'll create a new issue for that.
