### ISSUE TITLE
[RFC] Middleware based design

### ISSUE THREAD

**Issue by eirikurn** [aranja/tux#16]
A render pipeline would allow different functionality to be plugged in. With special logic for client vs server.

A middleware may:

* Wrap react element (e.g. to set up react context, layout).
* Wrap render? (e.g. to detect rendered styles like glamor).
* Pass props/context to <Html /> (meta tags, store, styles, data for hydrating).

```javascript
import tux, { startClient } from 'tux'
tux.use(redux())
tux.use(helmet())
tux.use(glamor())
tux.use(router(routes))
startClient(tux)
```

## Examples of middlewares:

* Data API
* Style renderer
* Code split optimiser
* Router
* Redux
* Helmet
* Admin
* Scroll history

## More code examples:

```javascript
export const redux = (reducers) => () => ({
  async element(next, context) => {
    context.store = createStore(reducers, context.data.redux)
    context.dispatch = context.store.dispatch
    const element = await next()

    return (
      <Provider store={context.store}>
        {element}
      </Provider>
    )
  }

  onServerRender(render, context) => {
    render()
    context.data.redux = context.store.getState()
  }
})

export const helmet = () => ({
  onServerRender(render, context) => {
    render()
    context.htmlProps.helmet = Helmet.rewind()
  }
})
```

**Comment by rthor** [comment]
Kept up to date [here](https://github.com/aranja/tux-rfcs/blob/middlewares/text/0000-middlewares.md)
