### ISSUE TITLE
Megadraft bug. EditableInline text-format button visible on EditableModal area.

### ISSUE THREAD

**Issue by DavidBachmann** [aranja/tux#19]
Recreate by

1. selecting a EditableInline field:

![image](https://cloud.githubusercontent.com/assets/8494120/23366845/20db5e88-fd00-11e6-879d-cb5e7287f285.png)

2. while it's still active, triple (yes, triple) click a EditableModal text-area.

![image](https://cloud.githubusercontent.com/assets/8494120/23366879/47ef03f8-fd00-11e6-9fe4-620fb0303407.png)

**Comment by rthor** [comment]
I think this is a side-effect of something else. Can't reproduce. If we see this later, we will reopen this.
