### ISSUE TITLE
Importing svg doesn't work

### ISSUE THREAD

**Issue by DavidBachmann** [aranja/tux#53]
![image](https://cloud.githubusercontent.com/assets/8494120/23895676/7da91a66-089e-11e7-8589-cf1350775b20.png)

`<img class="SocialPlug-logo" src="data:application/svg+xml;base64,PD94bWwgdmVy...`

`import twitterLogo from './Twitter.svg'` in '`tux-example-site/src/components/SocialPlug/index.js`

**Comment by eirikurn** [comment]
Waiting for fix from upstream: https://github.com/mozilla-neutrino/neutrino-dev/pull/115

**Comment by eirikurn** [comment]
That only took a minute (literally). Now let's see if they publish a new version soon.

**Comment by eirikurn** [comment]
This should be fixed now.
