### ISSUE TITLE
Make TuxModal field id consistent with inline editor

### ISSUE THREAD

**Issue by eirikurn** [aranja/tux#62]
I love that there is almost nothing contentful specific in tux anymore.

One remaining thing is that TuxModal still hard codes `model.fields[...]` instead of sharing dynamic field name logic with the inline editor.

After adding this support, we can change the contentful schemas to have `field: 'fields.title'` instead of `field: 'title'`.

**Comment by baering** [comment]
This is a duplicate of #54

**Comment by baering** [comment]
Fixed in #67
